pull_request_template.md
Commits to robots.txt landing in master will be pushed to production automatically. Only merge pull requests that you're confidant should be pushed to production.
=> Fixed typo

www.1stdibs.com/robots.txt
ticket: https://1stdibs.atlassian.net/browse/FTV-234
=> disallow shipping-complimentary

www.1stdibs.com/robots.txt
ticket: https://1stdibs.atlassian.net/browse/FTV-369
=> refactor: rename disallow shipping-free

www.1stdibs.com/robots.txt
=> feat: FTV-378 - disallow url with sale param

www.1stdibs.com/robots.txt
Related: https://github.com/1stdibs/dibs-components/pull/2030
=> CONT-1246 add white glove query params

www.1stdibs.com/robots.txt
=> throttling pinterest due to them DOSing us

www.1stdibs.com/robots.txt
Related to https://github.com/1stdibs/dibs-graphql/pull/6907
=> GROWTH-4812 Remove Noindex: */room/*

www.1stdibs.com/robots.txt
=> SALESFORCE-1948 disallow salesforce form URLs

www.1stdibs.com/robots.txt
=> fixed placement of art test allow directives

www.1stdibs.com/robots.txt
=> GROWTH-4739 : disallow vpv

www.1stdibs.com/robots.txt
=> GROWTH-4968 : Jewelry test - allow all jewelry parameterized pages

a.1stdibscdn.com/robots.txt
=> don't disallow srcset images

www.1stdibs.com/robots.txt
=> feat: VERTICALS-72 disallow private-sale

www.1stdibs.com/robots.txt
=> removed params st, customizable, item-type

www.1stdibs.com/robots.txt
=> feat: GROWTH-5269 disallow buy page with ?page param

www.1stdibs.com/robots.txt
=> PERF-92 - disallow buyer-base

www.1stdibs.com/robots.txt
https://1stdibs.atlassian.net/browse/GROWTH-6055
=> GROWTH-6055: Disallow: /*topic=*

www.1stdibs.com/robots.txt
=> SDATA-983 add frame to disallow

www.1stdibs.com/robots.txt
=> GROWTH-6266 Allow only the exact /soa/graphql/ endpoint

www.1stdibs.com/robots.txt
=> Added Allow support for graphql query params

www.1stdibs.com/robots.txt
list pulled from this discussion: https://1stdibs.slack.com/archives/CB30ZSLJC/p1687900626707289?thread_ts=1687898637.129279&cid=CB30ZSLJC
=> INTL-3633 Update robots.txt for IT

CODEOWNERS, README.md
We've given some SEO people permission to edit the `robots.txt` file, but they'll need eng input to review and deploy. Ideally, even the deployment would be automated, but at the very least, the job is extremely fast (takes < 1 minute) so hopefully shouldn't be too disruptive for y'all!
=> Update README.md and add CODEOWNERS

www.1stdibs.com/robots.txt
https://1stdibs.atlassian.net/browse/FI-2292
=> FI-2292 ban GoogleOther from /photos

www.1stdibs.com/robots.txt
https://1stdibs.atlassian.net/browse/FI-2358
see https://1stdibs.slack.com/archives/CB30ZSLJC/p1721137973073149
=> FI-2358 disallow WP searches

www.1stdibs.com/robots.txt
Ticket:
https://1stdibs.atlassian.net/browse/SEO-451
=> feat: SEO-451 disallow PetalBot
